Publish workflow: add Update Readme file jdk section job

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -243,3 +243,43 @@ jobs:
       DOCKER_PRIVATE_KEY_ID: ${{ secrets.DOCKER_PRIVATE_KEY_ID }}
       DOCKER_PRIVATE_KEY: ${{ secrets.DOCKER_PRIVATE_KEY }}
       DOCKER_PRIVATE_KEY_PASSPHRASE: ${{ secrets.DOCKER_PRIVATE_KEY_PASSPHRASE }}
+
+  update-zulu-jdks-readme:
+    name: "Update Readme file jdk section"
+    needs: build-jdk-images
+    runs-on: ubuntu-latest
+    steps:
+    - name: Checkout repository
+      uses: actions/checkout@v4
+    - name: Check latest jdk versions
+      run: |
+        if ! grep -q '<!-- GHASTART -->' README.md; then
+          echo "Error: Cannot find <!-- GHASTART --> md comment in Readme.md file! Abort"
+          exit 1
+        fi
+        if ! grep -q '<!-- GHAEND -->' README.md; then
+          echo "Error: Cannot find <!-- GHAEND --> md comment in Readme.md file! Abort"
+          exit 1
+        fi
+        echo "Fetching latest versions of JDK (${jdk_list}):"
+        for major_jdk_version in ${jdk_list//,/ }; do
+          latestversion=$(curl -fsSL -X GET "https://api.azul.com/metadata/v1/zulu/packages/?java_version=${major_jdk_version}&os=ubuntu&arch=amd&java_package_type=jdk&javafx_bundled=true&release_status=ga&availability_types=CA&certifications=tck&page=1&page_size=1"   -H "accept: application/json" | jq -r '.[].java_version | join(",")')
+          if [ -z "${latestversion}" ]; then
+            echo "Error: Cannot find latest version for JDK ${major_jdk_version}! Abort!"
+            exit 1
+          fi
+          export JDK${major_jdk_version}_VERSION=$(echo ${latestversion} | sed 's/,/./g')
+        done
+        perl -pe 's/\$\{([^}]+)\}/$ENV{$1} || ""/ge' .github/table-template.md | column -t -s '|' -o '|' > /tmp/mdtable
+        sed '/<!-- GHASTART -->/q' README.md > /tmp/newreadme
+        cat /tmp/mdtable >> /tmp/newreadme
+        sed -n '/<!-- GHAEND -->/,$p' README.md >> /tmp/newreadme
+        cp -f /tmp/newreadme README.md
+        git status
+        git config --global user.email "exo-swf@exoplatform.com"
+        git config --global user.name "eXo Software Factory"
+        git add README.md
+        git diff-index --quiet HEAD || git commit -m "Automated JDK versions README update"
+        git push origin HEAD
+      env:
+        jdk_list: 8,11,17,21
